"""init

Revision ID: 782e388bfbf1
Revises:
Create Date: 2025-11-16 08:59:18.221960

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "782e388bfbf1"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "degree",
        sa.Column("title", sa.TEXT(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_degree")),
    )
    op.create_table(
        "department",
        sa.Column("title", sa.TEXT(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_department")),
    )
    op.create_table(
        "educational_program_partner",
        sa.Column("title", sa.TEXT(), nullable=False),
        sa.Column(
            "partner_type",
            sa.Enum(
                "OO",
                "Industry",
                "Science",
                "Other",
                name="educationalprogrampartnerenum",
            ),
            nullable=False,
        ),
        sa.Column("hours", sa.Integer(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_educational_program_partner")
        ),
    )
    op.create_table(
        "field_of_study",
        sa.Column(
            "code",
            sa.String(length=8),
            nullable=False,
            comment="Format: XX.XX.XX",
        ),
        sa.Column("title", sa.TEXT(), nullable=False),
        sa.Column("title_short", sa.String(length=5), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "code ~ '^[0-9]{2}\\.[0-9]{2}\\.[0-9]{2}$'",
            name=op.f("ck_field_of_study_ck_field_of_study_code_format"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_field_of_study")),
        sa.UniqueConstraint("code", name=op.f("uq_field_of_study_code")),
    )
    op.create_table(
        "school",
        sa.Column("code", sa.String(length=3), nullable=False),
        sa.Column("title", sa.TEXT(), nullable=False),
        sa.Column("title_short", sa.String(length=20), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_school")),
        sa.UniqueConstraint("code", name=op.f("uq_school_code")),
    )
    op.create_table(
        "educational_program",
        sa.Column("title", sa.TEXT(), nullable=False),
        sa.Column("title_short", sa.String(length=5), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("school_id", sa.Integer(), nullable=True),
        sa.Column("degree_id", sa.Integer(), nullable=True),
        sa.Column(
            "network_form",
            sa.Enum(
                "NO",
                "FEFU_BASIC",
                "FEFU_PARTICIPANT",
                "UNKNOWN",
                name="networkformenum",
            ),
            nullable=True,
        ),
        sa.Column(
            "educational_form",
            sa.Enum("OFFLINE", "ONLINE", "BOTH", name="educationalformenum"),
            nullable=True,
        ),
        sa.Column(
            "educational_standard_type",
            sa.Enum(
                "FGOS_VO_3_PLUS", "OS_VO_DVFU", name="educationalstandardenum"
            ),
            nullable=True,
        ),
        sa.Column(
            "language",
            sa.Enum(
                "RUSSIAN",
                "ENGLISH",
                "PARTIALLY_ENGLISH",
                name="educationalprogramlanguagetypeenum",
            ),
            nullable=True,
        ),
        sa.Column("language_hours", sa.Integer(), nullable=True),
        sa.Column("standard_duration_months", sa.Integer(), nullable=True),
        sa.Column("poa_accreditation_company", sa.TEXT(), nullable=True),
        sa.Column("poa_accreditation_expiry", sa.Date(), nullable=True),
        sa.Column("state_accreditation_expiry", sa.Date(), nullable=True),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["degree_id"],
            ["degree.id"],
            name=op.f("fk_educational_program_degree_id_degree"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["educational_program.id"],
            name=op.f("fk_educational_program_parent_id_educational_program"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["school.id"],
            name=op.f("fk_educational_program_school_id_school"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_educational_program")),
    )
    op.create_table(
        "user",
        sa.Column("email", sa.TEXT(), nullable=True),
        sa.Column("phone", sa.TEXT(), nullable=True),
        sa.Column("position", sa.TEXT(), nullable=True),
        sa.Column("full_name", sa.TEXT(), nullable=True),
        sa.Column("internal_number", sa.TEXT(), nullable=True),
        sa.Column(
            "access_level",
            sa.Enum("director", "manager", "admin", name="accesslevelenum"),
            nullable=True,
        ),
        sa.Column("school_id", sa.BigInteger(), nullable=True),
        sa.Column("field_of_study_id", sa.BigInteger(), nullable=True),
        sa.Column("department_id", sa.BigInteger(), nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["department.id"],
            name=op.f("fk_user_department_id_department"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["field_of_study_id"],
            ["field_of_study.id"],
            name=op.f("fk_user_field_of_study_id_field_of_study"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["school_id"],
            ["school.id"],
            name=op.f("fk_user_school_id_school"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
    )
    op.create_table(
        "educational_program_active",
        sa.Column("educational_program_id", sa.Integer(), nullable=False),
        sa.Column("field_of_study_id", sa.Integer(), nullable=False),
        sa.Column("start_year", sa.Integer(), nullable=False),
        sa.Column("end_year", sa.Integer(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["educational_program_id"],
            ["educational_program.id"],
            name=op.f(
                "fk_educational_program_active_educational_program_id_educational_program"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["field_of_study_id"],
            ["field_of_study.id"],
            name=op.f(
                "fk_educational_program_active_field_of_study_id_field_of_study"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_educational_program_active")
        ),
        sa.UniqueConstraint(
            "field_of_study_id",
            "start_year",
            "end_year",
            name="uq_field_of_study_start_end",
        ),
    )
    op.create_table(
        "educational_program_to_partner",
        sa.Column("educational_program_id", sa.Integer(), nullable=False),
        sa.Column("partner_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["educational_program_id"],
            ["educational_program.id"],
            name=op.f(
                "fk_educational_program_to_partner_educational_program_id_educational_program"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["partner_id"],
            ["educational_program_partner.id"],
            name=op.f(
                "fk_educational_program_to_partner_partner_id_educational_program_partner"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_educational_program_to_partner")
        ),
        sa.UniqueConstraint(
            "educational_program_id",
            "partner_id",
            name="uq_educational_program_partner",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("educational_program_to_partner")
    op.drop_table("educational_program_active")
    op.drop_table("user")
    op.drop_table("educational_program")
    op.drop_table("school")
    op.drop_table("field_of_study")
    op.drop_table("educational_program_partner")
    op.drop_table("department")
    op.drop_table("degree")
    # ### end Alembic commands ###
