events {}

http {
    types_hash_bucket_size 1024;
    client_max_body_size 2000M;
    types_hash_max_size 4096;
    server_tokens off;
    server_name_in_redirect on;
    server_names_hash_bucket_size 64;
    include /etc/nginx/mime.types;

    upstream ep_register_ui {
        server ep-register-ui:80;
    }

    server {
        listen 80;

        # 1. Add the Docker internal DNS resolver
        resolver 127.0.0.11 valid=30s;

        location / {
            # 2. Set the hostname as a variable
            set $ui_backend ep-register-ui;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # 3. Use the variable in proxy_pass
            proxy_pass http://$ui_backend:80;
        }

        location /api/v1 {
            set $api_backend api:8000;
            proxy_set_header Host $http_host;
            proxy_pass http://$api_backend;
        }
    }
}