import src.models.degree  # noqa
import src.models.department  # noqa
import src.models.educational_program  # noqa
import src.models.educational_program_partner  # noqa
import src.models.enum  # noqa
import src.models.field_of_study  # noqa
import src.models.school  # noqa
import src.models.user  # noqa
import src.models.auth  # noqa
import src.models.tag  # noqa